/**
 * AUTO-GENERATED by barrelize.mjs
 * Do not edit manually - run `pnpm barrels` to regenerate
 */

export * from './debug-typography';
export * from './densityAdapter';
export * from './layoutConfig';
export * from './rtl';
export * from './semanticSizing';
export * from './useMotion';

// Re-export transitions as canonical namespace (tree-shakeable)
export * as transitions from '../tokens/transitions';
