/**
 * Checkbox - Production-grade SKIN-driven Flowbite wrapper
 * 
 * Generated by: pnpm ds:new Checkbox
 * Pattern: Wrap Flowbite component + apply SKIN variables
 * 
 * Features:
 * - 5 variants (default, success, warning, danger, info)
 * - Wraps Flowbite Checkbox (battle-tested foundation)
 * - SKIN-driven styling (design tokens only)
 * - A11y: Inherits from Flowbite
 * - Diagnostics: data-* attributes for debugging
 */

import './Checkbox.css';

import { Checkbox as FlowbiteCheckbox } from 'flowbite-react';
import { ComponentProps } from 'react';
import { twMerge } from 'tailwind-merge';

import { CheckboxVariant as CheckboxVariantType } from '../control/variants.config';
import { CHECKBOX_SKIN } from '../registry/skins/checkbox.skin';

// Re-export for backward compatibility
export type { CheckboxVariantType as CheckboxVariant };

/**
 * SKIN imported from registry - single source of truth
 * Local component consumes; never defines
 */
const SKIN = CHECKBOX_SKIN;

export type CheckboxProps = ComponentProps<typeof FlowbiteCheckbox> & {
  /**
   * Semantic variant (DS layer)
   * @default 'default'
   */
  variant?: CheckboxVariantType;
};

/**
 * Checkbox - Flowbite wrapper with SKIN
 * 
 * Wraps Flowbite's Checkbox component and applies SKIN variables.
 * All Flowbite props pass through; SKIN adds semantic variants.
 * 
 * @example
 * ```tsx
 * <Checkbox variant="default" checked>
 *   Label text
 * </Checkbox>
 * ```
 */
export function Checkbox({
  variant = 'default',
  className,
  style,
  ...rest
}: CheckboxProps) {
  // Get skin variables for this variant
  const skin = SKIN[variant];
  
  return (
    <FlowbiteCheckbox
      data-component="checkbox"
      data-variant={variant}
      className={twMerge(className)}
      style={{ ...skin, ...style } as any}
      {...rest as any}
    />
  );
}

// Component-specific variant exported above as CheckboxVariant
