/**
 * Radio - Production-grade SKIN-driven Flowbite wrapper
 * 
 * Generated by: pnpm ds:new Radio
 * Pattern: Wrap Flowbite component + apply SKIN variables
 * 
 * Features:
 * - 5 variants (default, success, warning, danger, info)
 * - Wraps Flowbite Radio (battle-tested foundation)
 * - SKIN-driven styling (design tokens only)
 * - A11y: Inherits from Flowbite
 * - Diagnostics: data-* attributes for debugging
 */

import './Radio.css';

import { Radio as FlowbiteRadio } from 'flowbite-react';
import { ComponentProps } from 'react';
import { twMerge } from 'tailwind-merge';

import { RadioVariant as RadioVariantType } from '../control/variants.config';
import { RADIO_SKIN } from '../registry/skins/radio.skin';

// Re-export for backward compatibility
export type { RadioVariantType as RadioVariant };

/**
 * SKIN imported from registry - single source of truth
 * Local component consumes; never defines
 */
const SKIN = RADIO_SKIN;

export type RadioProps = ComponentProps<typeof FlowbiteRadio> & {
  /**
   * Semantic variant (DS layer)
   * @default 'default'
   */
  variant?: RadioVariantType;
};

/**
 * Radio - Flowbite wrapper with SKIN
 * 
 * Wraps Flowbite's Radio component and applies SKIN variables.
 * All Flowbite props pass through; SKIN adds semantic variants.
 * 
 * @example
 * ```tsx
 * <Radio variant="default" checked>
 *   Label text
 * </Radio>
 * ```
 */
export function Radio({
  variant = 'default',
  className,
  style,
  ...rest
}: RadioProps) {
  // Get skin variables for this variant
  const skin = SKIN[variant];
  
  return (
    <FlowbiteRadio
      data-component="radio"
      data-variant={variant}
      className={twMerge(className)}
      style={{ ...skin, ...style } as any}
      {...rest as any}
    />
  );
}

// Component-specific variant exported above as RadioVariant
