/**
 * Toggle - Production-grade SKIN-driven Flowbite wrapper
 * 
 * Generated by: pnpm ds:new Toggle
 * Pattern: Wrap Flowbite component + apply SKIN variables
 * 
 * Features:
 * - 5 variants (default, success, warning, danger, info)
 * - Wraps Flowbite ToggleSwitch (battle-tested foundation)
 * - SKIN-driven styling (design tokens only)
 * - A11y: Inherits from Flowbite
 * - Diagnostics: data-* attributes for debugging
 */

import './Toggle.css';

import { ToggleSwitch as FlowbiteToggleSwitch } from 'flowbite-react';
import { ComponentProps } from 'react';
import { twMerge } from 'tailwind-merge';

import { ToggleVariant as ToggleVariantType } from '../control/variants.config';
import { TOGGLE_SKIN } from '../registry/skins/toggle.skin';

// Re-export for backward compatibility
export type { ToggleVariantType as ToggleVariant };

/**
 * SKIN imported from registry - single source of truth
 * Local component consumes; never defines
 */
const SKIN = TOGGLE_SKIN;

export type ToggleProps = ComponentProps<typeof FlowbiteToggleSwitch> & {
  /**
   * Semantic variant (DS layer)
   * @default 'default'
   */
  variant?: ToggleVariantType;
};

/**
 * Toggle - Flowbite wrapper with SKIN
 * 
 * Wraps Flowbite's ToggleSwitch component and applies SKIN variables.
 * All Flowbite props pass through; SKIN adds semantic variants.
 * 
 * @example
 * ```tsx
 * <Toggle variant="default" checked>
 *   Content
 * </Toggle>
 * ```
 */
export function Toggle({
  variant = 'default',
  className,
  style,
  ...rest
}: ToggleProps) {
  // Get skin variables for this variant
  const skin = SKIN[variant];
  
  return (
    <FlowbiteToggleSwitch
      data-component="toggle"
      data-variant={variant}
      className={twMerge(className)}
      style={{ ...skin, ...style } as any}
      {...rest as any}
    />
  );
}

// Component-specific variant exported above as ToggleVariant
