---
to: packages/ds/src/primitives/<%= name %>.tsx
---
<% PascalName = name %>/**
 * <%= PascalName %> - <%= description %>
 * 
 * @generated by hygen ds primitive new
 */

import * as React from 'react';

export interface <%= PascalName %>Props extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Child content
   */
  children?: React.ReactNode;
}

/**
 * <%= PascalName %> component
 */
export const <%= PascalName %>: React.FC<<%= PascalName %>Props> = ({
  children,
  className = '',
  ...props
}) => {
  return (
    <div 
      className={`ds-<%= name.toLowerCase() %> ${className}`}
      data-component="<%= PascalName %>"
      {...props}
    >
      {children}
    </div>
  );
};

<%= PascalName %>.displayName = '<%= PascalName %>';
