---
to: packages/ds/src/primitives/<%= name %>.stories.tsx
---
<% PascalName = name %>/**
 * <%= PascalName %> Stories
 * 
 * @generated by hygen ds primitive new
 */

import type { Meta, StoryObj } from '@storybook/react';
import { <%= PascalName %> } from './<%= PascalName %>';

const meta: Meta<typeof <%= PascalName %>> = {
  title: 'Primitives/<%= PascalName %>',
  component: <%= PascalName %>,
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof <%= PascalName %>>;

export const Default: Story = {
  render: () => (
    <<%= PascalName %>>
      <%= PascalName %> content
    </<%= PascalName %>>
  ),
};
