name: Auto-Fix Housekeeping
on:
  schedule: [{ cron: '0 6 * * *' }] # daily 06:00 UTC
  workflow_dispatch:

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false }
      - uses: pnpm/action-setup@v3
        with: { version: 8 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile

      - name: Regenerate tokens
        run: pnpm tokens:codegen

      - name: Barrelize
        run: pnpm barrels

      - name: Import fixes
        run: pnpm imports:fix

      - name: Build & Update API reports
        run: |
          pnpm -F @intstudio/ds build
          pnpm -F @intstudio/forms build
          pnpm -F @intstudio/ds api:extract
          pnpm -F @intstudio/forms api:extract

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/auto-fix-housekeeping
          title: "🤖 Auto-fix: housekeeping (tokens/barrels/imports/api)"
          body: |
            Automated housekeeping:
            - tokens codegen
            - barrels regenerated (DS + Forms)
            - import fixes (DS + Forms)
            - API reports updated (DS + Forms)
          commit-message: "chore(housekeeping): tokens/barrels/imports/api"
          labels: chore, automerge
