name: Cascade OS Enforcement

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  lint-overlay-rules:
    name: ESLint Overlay Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -w lint

  overlay-smoke:
    name: Overlay Smoke Tests (@375x480)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -w build
      - run: npx playwright install --with-deps
      - run: npx playwright test tests/overlay.spec.ts --reporter=line

  design-tokens-check:
    name: Verify Design Tokens (No Magic Numbers)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for magic z-index values
        run: |
          if git grep -n "zIndex.*[0-9]\{3,\}" -- "*.tsx" "*.ts" ":!**/tokens.ts" ":!**/*.spec.ts"; then
            echo "❌ Found magic z-index numbers. Use getZIndex() from tokens.ts"
            exit 1
          fi
      - name: Check for hardcoded timing values (warn only)
        run: |
          if git grep -n "transition.*[0-9]\+ms" -- "*.tsx" "*.ts" ":!**/tokens.ts"; then
            echo "⚠️ Found hardcoded timing. Consider OVERLAY_TOKENS.timing"
          fi

  typography-compliance:
    name: Typography System Compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Typography Compliance
        run: |
          chmod +x .github/scripts/check-typography.sh
          .github/scripts/check-typography.sh
