name: Forms CI

on:
  push:
    paths: ['packages/forms/**', '.github/workflows/forms-ci.yml']
  pull_request:
    paths: ['packages/forms/**', '.github/workflows/forms-ci.yml']

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with: 
          version: 8
      
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build Forms
        run: pnpm -F @intstudio/forms build
      
      - name: TypeScript check
        run: pnpm -F @intstudio/forms typecheck
      
      - name: Run tests
        run: pnpm -F @intstudio/forms test
      
      - name: Dependency boundaries
        run: pnpm depgraph:check
