name: Repo Health

on:
  schedule:
    - cron: "0 8 * * *"  # Daily at 8am UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run full health check
        run: pnpm doctor
