name: Repo Hygiene

on:
  pull_request:
    paths: ['packages/**', 'repo.imports.yaml', 'scripts/**']
  push:
    branches: [main, feat/*]
    paths: ['packages/**', 'repo.imports.yaml', 'scripts/**']

jobs:
  hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with: 
          version: 8
      
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Regenerate barrels
        run: pnpm barrels
      
      - name: Check for barrel drift
        run: |
          if ! git diff --quiet packages/**/index.ts; then
            echo "❌ Barrels are out of sync! Run 'pnpm barrels' locally."
            git diff packages/**/index.ts
            exit 1
          fi
      
      - name: Import Doctor check
        run: pnpm imports:check
      
      - name: Dependency boundaries
        run: pnpm run depgraph:check || true
