name: Storybook CI

on:
  pull_request:
    paths:
      - 'packages/**'
      - '.storybook/**'
      - 'apps/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  push:
    branches:
      - main

jobs:
  storybook:
    name: Build & Test Storybook
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm build
      
      - name: Build Storybook
        run: pnpm sb:build
      
      - name: Run interaction tests
        run: pnpm sb:test:ci
      
      - name: Upload Storybook artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static/
          retention-days: 7
