name: Token Snapshot Check

on:
  pull_request:
    paths:
      - 'packages/wizard-react/src/tokens/**'
      - 'contracts/tokens@*.json'

jobs:
  check-token-changes:
    name: Validate Token Changes
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check if tokens changed
        id: token-check
        run: |
          # Check if token files changed
          TOKEN_FILES_CHANGED=$(git diff origin/main --name-only | grep -c "packages/wizard-react/src/tokens/" || true)
          
          # Check if snapshot changed
          SNAPSHOT_CHANGED=$(git diff origin/main --name-only | grep -c "contracts/tokens@" || true)
          
          echo "token_files_changed=$TOKEN_FILES_CHANGED" >> $GITHUB_OUTPUT
          echo "snapshot_changed=$SNAPSHOT_CHANGED" >> $GITHUB_OUTPUT
          
          echo "## Token Change Detection" >> $GITHUB_STEP_SUMMARY
          echo "Token files changed: $TOKEN_FILES_CHANGED" >> $GITHUB_STEP_SUMMARY
          echo "Snapshot changed: $SNAPSHOT_CHANGED" >> $GITHUB_STEP_SUMMARY
      
      - name: Require tokens-change label
        if: steps.token-check.outputs.token_files_changed != '0'
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            const hasLabel = labels.includes('tokens-change');
            
            if (!hasLabel) {
              core.setFailed('❌ Token files changed but PR missing "tokens-change" label');
              
              // Post comment
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.name,
                issue_number: context.issue.number,
                body: `## ⚠️ Token Change Detected
                
                Token files have changed but this PR is missing the \`tokens-change\` label.
                
                **Why this matters:**
                - Token changes affect ALL components
                - May break existing designs
                - Requires careful review
                - Should trigger new snapshot
                
                **Required actions:**
                1. Add \`tokens-change\` label to this PR
                2. Update token snapshot: \`npm run tokens:snapshot\`
                3. Document changes in PR description
                
                **Changed files:**
                ${context.payload.pull_request.changed_files} files changed
                `
              });
            } else {
              core.info('✅ tokens-change label present');
            }
      
      - name: Require snapshot update
        if: steps.token-check.outputs.token_files_changed != '0' && steps.token-check.outputs.snapshot_changed == '0'
        run: |
          echo "❌ Token files changed but snapshot not updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Run: npm run tokens:snapshot" >> $GITHUB_STEP_SUMMARY
          exit 1
      
      - name: Validate snapshot format
        if: steps.token-check.outputs.snapshot_changed != '0'
        run: |
          # Find the latest snapshot
          SNAPSHOT=$(ls -t contracts/tokens@*.json | head -1)
          
          echo "Validating: $SNAPSHOT"
          
          # Check JSON is valid
          if ! jq empty "$SNAPSHOT" 2>/dev/null; then
            echo "❌ Invalid JSON in snapshot"
            exit 1
          fi
          
          # Check required fields
          if ! jq -e '.version' "$SNAPSHOT" >/dev/null; then
            echo "❌ Missing version field"
            exit 1
          fi
          
          if ! jq -e '.tokens' "$SNAPSHOT" >/dev/null; then
            echo "❌ Missing tokens field"
            exit 1
          fi
          
          echo "✅ Snapshot format valid"
      
      - name: Compare snapshots and assess impact
        if: steps.token-check.outputs.snapshot_changed != '0'
        run: |
          # Find current and previous snapshots
          CURRENT=$(ls -t contracts/tokens@*.json | head -1)
          PREVIOUS=$(ls -t contracts/tokens@*.json | head -2 | tail -1)
          
          if [ "$CURRENT" != "$PREVIOUS" ]; then
            echo "## Token Change Impact Assessment" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            # Count changes
            ADDED=$(jq -r '.metadata.totalTokens' "$CURRENT")
            PREV_TOTAL=$(jq -r '.metadata.totalTokens' "$PREVIOUS")
            DIFF=$((ADDED - PREV_TOTAL))
            
            echo "**Token count change:** $PREV_TOTAL → $ADDED (${DIFF:+$DIFF})" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            # Risk assessment
            if [ $DIFF -gt 10 ]; then
              echo "⚠️ **Risk: HIGH** - More than 10 tokens changed" >> $GITHUB_STEP_SUMMARY
            elif [ $DIFF -gt 5 ]; then
              echo "⚠️ **Risk: MEDIUM** - 5-10 tokens changed" >> $GITHUB_STEP_SUMMARY
            else
              echo "✅ **Risk: LOW** - Minor token change" >> $GITHUB_STEP_SUMMARY
            fi
            
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Impacted Components" >> $GITHUB_STEP_SUMMARY
            echo "- All \`ds-button\` variants (7 total)" >> $GITHUB_STEP_SUMMARY
            echo "- All \`ds-input\` fields (14 total)" >> $GITHUB_STEP_SUMMARY
            echo "- Custom components using CSS variables" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Required Actions" >> $GITHUB_STEP_SUMMARY
            echo "- [ ] Visual screenshots updated" >> $GITHUB_STEP_SUMMARY
            echo "- [ ] Contrast tests pass (4.5:1)" >> $GITHUB_STEP_SUMMARY
            echo "- [ ] Dark theme adjusted" >> $GITHUB_STEP_SUMMARY
            echo "- [ ] Multi-brand themes updated" >> $GITHUB_STEP_SUMMARY
            
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "<details><summary>Token Diff</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            diff <(jq -S . "$PREVIOUS") <(jq -S . "$CURRENT") >> $GITHUB_STEP_SUMMARY || true
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Success summary
        if: success()
        run: |
          echo "✅ Token snapshot validation passed" >> $GITHUB_STEP_SUMMARY
